%% symbolic variables and constants
v0 = 110 * 5/18; % m/s
g = 9.81; % m/s^2
 
% Max. height
syms m Hmax positive
E0 = m*v0^2/2;
Ef = m*g*Hmax;
Hmax = solve(E0 == Ef, Hmax); 
fprintf('Maximum height up the hill: %0.3f m \n',vpa(Hmax));
% For m = 750
m = 750; % kg
H = 22; % m
% By using Energy
E02 = m*v0^2/2;
Ef2 = m*g*H; 
frictionW = Ef2 - E02;
fprintf('Thermal energy generated by friction: %0.3f J \n',vpa(-frictionW));
% for a slope of 2.5
th = 2.5; % degrees
D = H/ sind(th);
f = -frictionW /D; % Work / distance
fprintf('Average force of friction: %0.3f N \n',vpa(f));